### ISSUE TITLE
probe expands in unexpected ways with Varnish-5.x

### ISSUE THREAD

**Issue by rnsanchez** [Dridi/libvmod-named#9] opened 2016-09-08 16:41 UTC
When compiling a VCL on Varnish-5.x, `probe` sometimes expands to empty:

    int __match_proto__(vcl_func_f)
    VGC_function_vcl_init(VRT_CTX)
    {
      VRT_handling(ctx, VCL_RET_OK);
      /* ... from ('/(...)/master.vcl' Line 22 Pos 5) */
      {
        {
          VRT_count(ctx, 1);
          Vmod_named_Func.director__init(ctx, &vo_D___bla, "D___bla",
            "80",
            0,
            ,  /* probe is empty here. */
            0,
            60,
            0,
            0,
            0,
            7200,
            2);
          VRT_handling(ctx, VCL_RET_OK);
          return (1);
        }
      }

Both Varnish and `libvmod-named` were `master` from Sep 8th.

**Comment by Dridi** [comment] 2016-09-08 16:53
Oh, that might be a bug in `vmodtool` or `libvcc`, do you have a VCL sample that breaks when compiled by varnish?

**Comment by rnsanchez** [comment] 2016-09-08 16:55
Does this help?

    new D___bla = named.director(
        port = "80",
        probe = probe_D__bla,
        first_lookup_timeout = 2s,
        ttl = 60s
    );

**Comment by Dridi** [comment] 2016-09-08 16:56
I'll do some testing and tell you, thanks for reporting!

**Comment by Dridi** [comment] 2016-09-08 17:05
I have a test case, thanks! It looks like a regression in Varnish, possibly caused by some refactoring in `libvcc`.

**Comment by rnsanchez** [comment] 2016-09-08 17:07
Awesome!  Happy you tracked it so quickly!

**Comment by Dridi** [comment] 2016-09-08 21:37
It was also easy to fix, I can now close this issue!

**Closed by Dridi** 2016-09-08 21:37 UTC
Labels: bug

**Comment by rnsanchez** [comment] 2016-09-09 13:17
@Dridi: the repository is unchanged, perhaps you forgot to push?

**Comment by Dridi** [comment] 2016-09-09 13:24
The bug was in Varnish, I commented in varnishcache/varnish-cache#2068.

**Comment by rnsanchez** [comment] 2016-09-09 13:28
Indeed, sorry for the noise.
